### ISSUE TITLE
DRG Suggestion

### ISSUE THREAD

**Issue by dstormcaller** [Grammernatzi/XIVComboPlugin#104]
Leading up to 6.1, they got my hopes up a bit by talking about trying to "reduce bloat and stress" from DRG. I hoped maybe they would remove one of the four damage boost oGCDs. That didn't happen, so I come to you, o reducer of bloat and stress. A few ideas:

1. Full Thrust Combo Plus - Adding Life Surge right before Full/Heaven's Thrust when it's off cooldown. In single target, as I understand it, Full Thrust is the only weaponskill worth using Life Surge on, so in single target I think it would be useful to have it appear in that combo, perhaps only during global cooldown like how that one Kaiten option used to work.

2. Coerthan Torment Combo Plus - Adding Life Surge right before Coerthan Torment. Same idea as above. In AOE my understanding is that Coerthan Torment is the only weaponskill worth using Life Surge on. Since DRG's AOE combo starts being unlocked fairly late, it could be worth setting this one to appear before whichever is the strongest AOE weaponskill unlocked.

3. Dragon Sight/Battle Litany/Lance Charge Feature - Just these three sharing a button. Dragon Sight and Battle Litany have the same cooldown time (120s). Lance Charge is at 60s. They all do fairly similar things, at least for casual players.

4. Stardiver to Nastrond Plus - Adding High Jump and Mirage Dive to the chain. So when High Jump is off cooldown, the ability will become High Jump, then Mirage Dive, then Geirskogul, then Nastrond, then Stardiver. My understanding is that this order is ideal in basically every situation, as you want to use Mirage Dive before Geirskogul to build up the Dragon Gauge and have Geirskogul become available right after the gauge is full.

Just a couple ideas I had to reduce how much my eyes are bouncing back and forth across my hotbars while playing Dragoon. I really like the job but I get a bit overwhelmed keeping track of all of it. Thanks for all the work you put into this plugin, I couldn't play without it! 😊

**Comment by Grammernatzi** [comment]
The only issue with the Life Surge thing is that it could be a bit wonky being inserted midcombo, and you also do want to save Life Surges for raid buffs, too, rather than using it the instant you have it available. You also want to use Life Surge on your 5th combo action in your opener, as well as during raid buffs if you've saved both, too. I could possibly do the Coerthan Torment version, though, since AoE doesn't really need optimization. Dragon Sight/Litany/Lance Charge is a fair one, I could add that just fine. And, the issue with the Jump > Dive > Geirskogul thing is that you sometimes do want to dive *after* Geirskogul as well (when you are about to reach 2 eyes), like if a boss is about to jump and you won't be able to attack them, or to align with your own buffs, or raid buffs. So I don't think those should really be so fiercely automated.

**Comment by dstormcaller** [comment]
Ah okay. I only play casually, avoiding raids, and haven't ever worried too much about party buff windows. That stuff is usually not on my radar.

I was sad they didn't remove Life Surge like they did with Kaiten because, at least the way I use it, it is pretty similar. Just a button you press before Full Thrust if it's available. But I suppose it is different in that Kaiten was almost always available and worth using, whereas Life Surge wasn't and could be saved for party buffs. That makes sense.

Anyway, thanks for the consideration!

**Comment by Grammernatzi** [comment]
Yeah, you never saved Kaiten, so it makes sense; that said, I could see them removing Life Surge and just buffing the potency of Full/Heaven's Thrust or Coerthan Torment. But, anyhow, I can still work on some of those features, so I will try so later.

**Comment by dstormcaller** [comment]
Thanks! I look forward to it! 😁
