### ISSUE TITLE
Feature request: Smart Acceleration

### ISSUE THREAD

**Issue by Zeemgeem** [Grammernatzi/XIVComboPlugin#112]
So with the current system as is, using acceleration will replace both verfire and verstone with verthunder and veraero, even if both are procced, which leads to situations where you can't use it without wasting a proc, and this can extend if you repeatedly proc. Without this plugin this is not an issue as verfire and verstone can't consume the acceleration charge. Could an option be added so it only replaces jolt, and not verfire/verstone procs?

**Comment by Grammernatzi** [comment]
The only issue with this is that it'd mess up the opener, since you're supposed to verthunder 3 times in a row, regardless of if it'd overwrite procs or not. Considering how little procs contribute to overall DPS, I feel it'd be better to just turn off the feature if you wanted to optimize it like this.

**Comment by Grammernatzi** [comment]
Added something that allows this in the newest version; added a disclaimer about the opener
