### ISSUE TITLE
Feature request: Black mage/ Summoner

### ISSUE THREAD

**Issue by serwiibox** [Grammernatzi/XIVComboPlugin#115]
**Black mage:**
-When "Triplecast" is on cooldown, replace it  with "Swiftcast".
-"Blizzard 3" becomes "blizzard 4" after using it. Also, It has to be compatible with the feature in the image.
-"Fire 1/3" becomes "Fire 4" after using it. Also, It has to be compatible with the feature in the image.

**Summoner:**
-"Energy Siphon" to "Energy drain" downgrade when doesn't have the level for it.
-"Painflare" to "Fester" downgrade when doesn't have the lvl for it.

![features](https://user-images.githubusercontent.com/110313910/182005016-44adf9f1-e9aa-45ef-a002-aa59be8a467d.png)

You are doing a great job!!!

**Comment by Grammernatzi** [comment]
I'm not subbed for a while, so I won't be able to add these soon, but, all of them sound alright, though, how would the fire 4 one work? You'd need to be able to use Fire 1/3 to keep your timer going, and I don't plan on making it automatically switch between the two based on the timer.

**Comment by serwiibox** [comment]
Oh, I undertand that about the timer. In that case can you change and add this about the BM
-When "Triplecast" is on cooldown, replace it with "Swiftcast" and the same thing with "Swiftcast".
-When "Manafont" is out of cooldown change it to "Lucid dreaming"
-Change Freeze/Flare switcher feature, when I put Frezze in my hotbar and I am not in UI/AF by default is set to Flare, I would like it to stay by default on Frezze when I am not in UI/AF.
-There is a Bug with Blizzard 4/Fire 4 to Xenoglossy movement feature and Frezze/Flare to Foul movement feature. When I don't have any target it doesn't work and when is working those two doesn't change sometimes at the same time and it bothers a bit (I have both activated).

![Screenshot_1](https://user-images.githubusercontent.com/110313910/182291053-c4111224-616e-4b1f-a451-669313dca201.png)
You can see in this image that flare is by default

![Screenshot_2](https://user-images.githubusercontent.com/110313910/182291109-8d39c312-9a09-4800-8ce5-2055f4e5c30d.png)
![Screenshot_3](https://user-images.githubusercontent.com/110313910/182291118-8f06082b-9040-4ad7-9acd-c942cc1b3fbc.png)
This two features are not working properly

I will be so grateful if you can add those thing for the BM and the Summoner.

**Comment by Grammernatzi** [comment]
The movement features are working properly from what I am seeing. The target logic seems unnecessary so I can remove that, but  the movement features won't activate if you either can't use foul/xenoglossy (no polyglot), or if you have triplecast/swiftcast up. Does it have issues otherwise? I haven't noticed, at all. Keep in mind they're not meant to replace your foul/xenoglossy buttons, especially since they don't even turn into foul before you get Xenoglossy.

**Comment by serwiibox** [comment]
Here are videos of the problem, sorry for quality.

https://gyazo.com/c69e62832e3129fa89e22d29439b499f
https://gyazo.com/9db27e691028119c7af191c6e676c9cf

 It seems that xenoglosy and foul don't change at the same time even though they meet the same conditions.
Also you could be right about Manafont but It could be an extra for those who use it.

**Comment by serwiibox** [comment]
About the target logic I think is not distracting, because I want to see it too if I'm not targeting the enemy but still in battle. It would be also nice when I'm out of battle.

**Comment by Grammernatzi** [comment]
I will have to take a look at what is causing the lag on the Xenoglossy,
then; I may have an idea as to what. But, again, I'm unsubscribed for a
while so I can't fix that stuff, and it's rather minor so I'm not really
rushing to spend the money to fix it at the moment. Once I get back with
6.2 later this month, I'll take a look at these things.

**Comment by serwiibox** [comment]
Thanks!

**Comment by serwiibox** [comment]
Hi, I noticed some things
<img width="275" alt="Screenshot_1" src="https://user-images.githubusercontent.com/110313910/185272211-862506b2-e44a-4392-a0aa-d07c86e2fc30.png">
In this one, the last characteristic, overwrites the others ''when you have no target'' it overwrites and when on battle it never shows up since I'm always targeting. It would be nice that it would show up even if I'm targeting.
Second:
<img width="278" alt="Screenshot_2" src="https://user-images.githubusercontent.com/110313910/185272381-2e3f1a48-5d32-4ce3-891f-0b60a695808b.png">
When the despair shows up on my hotbar even if I move it doesn't change to Xenoglossy. It feels strange because I can't use it properly.

Thanks in advance, I hope they can be fixed.

**Comment by Grammernatzi** [comment]
The despair thing is supposed to overwrite the xenoglossy, yes, I can fix
that. I would prefer not to change the other one though, you should have
the option to use thunder at all times regardless of if sharpcast is up or
not. If it didn't work this way, you would be forced to use sharpcast, even
if it wasn't full on charges.

**Comment by serwiibox** [comment]
Thank you!

**Comment by Grammernatzi** [comment]
Okay, so from what I am testing with the xeno and foul movement stuff: it's because they each have their own movement timer. So they end up a little unsynced. Though, this is the only case where there is every more than one movement timer on a job, so I'm not sure if it's really worth putting in the effort just to make sure they're all synced.

**Comment by serwiibox** [comment]
Thank you for your answer, it can be a bit annoying for people who use it and see it, it would be worth to fix since your addon is more popular and advanced than other addons that do the same thing. I would appreciate it if you fixed it. 
Thanks for your time.

**Comment by Grammernatzi** [comment]
It should be fixed now (Xenoglossy/Foul movement not being synced). I figure it was just cleaner to run it the way I am doing now, anyway, since it running on every single instance of an action being changed was a bit messy. I'll look at the other stuff as I go, though I'll be slow since I'm also doing 6.2 content.

**Comment by serwiibox** [comment]
Thank you so much! I'll wait for the next update then!

**Comment by Grammernatzi** [comment]
I just added the stuff from the other issues, since they were a lot less work overall; I'll work on this next, now, since it's the only thing remaining.

**Comment by Grammernatzi** [comment]
Alright, I added all of the ones I said I would (Triplecast to Swiftcast, Freeze/Flare being whatever they originally are when idle, ES to ED), except the Blizz 3 to Blizz 4 one because I'm not sure how really necessary that is for the work it'd require to implement (it doesn't save buttons or anything and it locks you out of using paradox when you want to), and Painflare to Fester level sync. Those just didn't feel like they'd be worth the effort atm, but if you disagree, I could do so.

**Comment by serwiibox** [comment]
Thank you for everything. Everything's perfect now!
