### ISSUE TITLE
SCH Auto Ruin II sometimes still tries to cast Broil IV

### ISSUE THREAD

**Issue by Matuno** [Grammernatzi/XIVComboPlugin#119]
Noticed that since the update, I see Broil IV turn into Ruin II on the hotbar very quickly, yet it will randomly still try to cast Broil IV when pressed even though the icon shows no sign of changing away from Ruin II.

Not sure how to best provide anything of note to diagnose, but let me know if there's anything I can do to help.

**Comment by Grammernatzi** [comment]
I'll take a look at it, can you tell me what your average frame rate is? That might help me discern what's causing the problem

**Comment by Matuno** [comment]
Sure thing, I'm capped at 165 and hitting 80 on average during fights it seems. Which I just realised is a whole other issue >.>

**Comment by Grammernatzi** [comment]
[Can you take the .dll in this .zip file](https://github.com/Grammernatzi/XIVComboPlugin/files/9438568/XIVComboExpandedest.zip) and put it in %appdata%\XIVLauncher\installedPlugins\XIVComboExpandedest\1.4.0.1, or whatever it is for you? That runs the player speed check more frequently, and I'm curious if that would either make it better, or make it worse. I'm probably going to rewrite the speed checking code anyway since it came to my attention that Dalamud now has a variable for player speed, so I can just use that to check instead of trying to calculate it via position.

**Comment by Matuno** [comment]
Will do, also recorded the issue in action on the current build if that's of any use to you.
Using the modified dll now and will get back to you shortly.

**Comment by Grammernatzi** [comment]
Testing using the IsPlayerMoving thing from ClientStructs and it seems to work fine. I'll probably just push that, hopefully it also doesn't have the same issue. I'm still curious what you might find, but this solution does seem to fix the issue either way.

**Comment by Matuno** [comment]
Experience from this first fight feels very positive at least. Oddly enough the icon in the hotbar changed as expected in the old build, but it would be casting the wrong spell (Broil) regardless.

So far it's good at least, I'll let you know when I run into new issues. Thanks for your good work and the quick fix!

**Comment by Grammernatzi** [comment]
No prob; hopefully the new build I just pushed fixes the issue, since it's using Dalamud's speed check now.

**Comment by Grammernatzi** [comment]
Whoops; it didn't build because I forgot to take out a line of code. It should be compiling now, and be ready in a few minutes.

**Comment by Grammernatzi** [comment]
I'll close the issue if it's been resolved so far; the new method of checking movement should work a lot better in general, hopefully, since it uses a game value now.
