### ISSUE TITLE
Suggestion: support for RDM 45/45 combo 

### ISSUE THREAD

**Issue by tanxpyox** [Grammernatzi/XIVComboPlugin#125]
Hi there. Just wondering if there can be an option to suppress the RDM melee combo replacement and force it to Enchanted Zwerchau (the "2")* when there is less than 50/50 mana but >= 45/45 mana. This has a use case when the RDM is at 45/45 but cannot afford to do one more dualcast for the conventional 1-2-3 melee combo (due to anticipated downtime or whatnot). With the proposed option, the RDM can instead execute a 2-2-2 to quickly generate three combo points and enter the verholy-scorch-resolution phase nonetheless.

*This cannot be 1 because 1 requires 20/20 mana to execute. And cannot be 3 because it has a longer GCD than 2.

**Comment by Grammernatzi** [comment]
This actually works? But, regardless, considering how situational it is, and the work to put in a new feature, couldn't you just put Zwerchau separately on your hotbar for those niche cases? That is what I tend to do for those sorts of situations; I use the combos more for general play, and use separate hotkeys for very niche uses, since I rarely press them, and that way I don't have to use those hotkeys for my actual combo 99% of the time.

**Comment by tanxpyox** [comment]
That works too, thanks!
