### ISSUE TITLE
Request: Soul Slice and Soul Scythe merged into the single-target and AoE combos

### ISSUE THREAD

**Issue by EnixLHQ** [Grammernatzi/XIVComboPlugin#126]
Requesting to have Soul Slice and Soul Scythe be a part of the single-target and AoE combos, respectively, whenever Soul Gauge is <50. Additionally, the Soul Slice to Soul Scythe feature could cooperate with this so that it detects which to use based on the combo string in use.

Currently, even though Soul Slice and Soul Scythe can switch between ST and AoE forms, it is an additional button that does not have an option to be bundled with the rest of the combo strings.

**Comment by Grammernatzi** [comment]
I don't know, this seems a little too automatic to me to be considered for single target. Not even just for cheating reasons, but because it could interfere with your own gauge management and cause you to be close to cap when you'd prefer to save for raid buffs. I could see it either being a feature for AOE or something that only happens if you're capped on charges, though. But neither would really save buttons and you need Soul Slice on your hot bar in general.
