### ISSUE TITLE
Some of Paladin's combos seem to be not working

### ISSUE THREAD

**Issue by Zakril** [Grammernatzi/XIVComboPlugin#131]
Thank you for your hard work, your fork is amazing addition to FFXIV, everything seems to be working after today's public Dalamud patch except few things in Paladin settings:

Change of Royal Autohrity Combo or its AoE equivalent Combo to Holy Spirit/Circle while under Divine Might do not work.

All the Confietor Combos that previously allowed to go from casting Holy Spirit/Circle to Confiteor Combo on end of Requiescat do not work probably beacasue Confietor does not need Requiescat stacks now instead Requiescat grants Confietor Ready.

**Comment by Zakril** [comment]
Now I noticed that also Atonement feature is gone which I suppose is intentional

**Comment by Grammernatzi** [comment]
I have been playing a lot of paladin for testing and those features you
mentioned are working fine for me. I will try it out on the public build in
a bit. And yes, the atonement feature is gone because it locks out the
ability to drop atonement, which is pretty vital to paladin rotation
(because they just decided that was worth keeping, I guess). Before, having
the goring blade combo allowed you to do so, but that's gone now.

**Comment by Zakril** [comment]
I am deeply sorry it appears that somehow my installation got corrupted 2 times in a row, after 3rd reinstall of plugin it seems to be working 100% fine
