### ISSUE TITLE
Paladin Requiescat -> Confetitor Rotation

### ISSUE THREAD

**Issue by Callindrill** [Grammernatzi/XIVComboPlugin#134]
When using Requiescat, it turns into confetitor and Holy Sprit/Circle are dealt with correctly. However, once the last stack of Req is gone (used by a Holy Circle, for instance), I'm left with Confetitor Ready, and Requiescat goes onto cooldown instead of staying Confetitor. You can see a picture of my hotbar here, with the Confet Ready status, and no stacks of Req. 

![image](https://user-images.githubusercontent.com/8518435/212590751-b1583913-a99e-4298-93d2-25c32e6d6096.png)

I am leaving confetitor on my hotbar for now to allow for the Requiescat -> Holy Spirit/Circle -> Confetitor combination.

I've tried deleting the plugin folders and reinstalling several times to no avail. Any help is appreciated, or if this is a bug, I'd love to see a fix. Thanks!

**Comment by Grammernatzi** [comment]
So, you're running out of Requiescat before you use Confiteor? I mean, you should be using Confiteor before that, but I think it's because the plugin checks if Requiescat is still up (as that's how Confiteor worked before). But, either way, it sounds like you're making a mistake and the combo doesn't work after making that mistake? I guess I don't want it to be punishing you more than usual, but you want to use Confiteor during Requiescat (usually first thing).

**Comment by Grammernatzi** [comment]
Changed, but please do not use Confiteor (and its combo) outside of Requiescat; it is meant to be used only in Requiescat and using it outside of it is a major damage loss. See this rotation for an example of how it should be used:

![image](https://user-images.githubusercontent.com/869037/212605534-d1d3022f-0a7c-41d5-953a-dea6d9e6011b.png)

**Comment by Callindrill** [comment]
Thanks for the fix and the tips!
