### ISSUE TITLE
Request: [RPR] & [DNC]

### ISSUE THREAD

**Issue by KieWil** [Grammernatzi/XIVComboPlugin#135]
Just want to say I'm really enjoying this plugin! I have a couple of requests:

[RPR]
Would it be possible to implement an option similar to '216 Blood Stalk to Grim Swathe Feature' (Blood Stalk turns into Grim Swathe if you are in the midst of your AoE combo) for Shadow of Death + Whorl of Death? 

[DNC]
Similarly, would it be possible to have an option that changes Reverse Cascade into Rising Windmill, and Fountainfall into Bloodshower after switching to the AoE moves Windmill + Bladeshower?

Thank you!

**Comment by Grammernatzi** [comment]
The reaper one I specifically did not do because you usually open with those moves, which would be impossible otherwise. But I suppose if you would really prefer to save buttons, then it could be done, as you'd only lose some damage on the first attack in AoE. As for the other one, I also didn't do that because there are some weird situations where you want to use the single Target version on two targets but you still want to use your AOE combo, but the damage difference is not likely super high.
