### ISSUE TITLE
Comboing TBN to Oblation

### ISSUE THREAD

**Issue by Luizgazen** [Grammernatzi/XIVComboPlugin#141]
Hey there, really like your plugin, some really good options in it, so i'd like to ask if you could add one more? substituting The Blackest Night for Oblation when it is on cd would make it much easier to use then, since we end up always using them together when both are up anyway... preferably setting the combo from TBN so we can keep Oblation alone on the hotbar to use the second charge independently when needed... thanks for the good work.

**Comment by Grammernatzi** [comment]
I see no issue with it, I'll add it in along with the other suggestion once I get back to the game within the next two weeks.

**Comment by Grammernatzi** [comment]
Adding this in the next patch, but it's worth noting that because of the multitude of ways you can apply Oblation/TBN (mouse over, focus target, targeting, <2>, whatever), I can only make it have this logic on yourself. So you would still need to manually press Oblation for other players unless targeting them directly, which I did add since it was possible.

**Comment by Luizgazen** [comment]
Thanks, just updated the plugin here and it works nicely
