### ISSUE TITLE
Various initial suggestions. (BLM, RDM, DNC)

### ISSUE THREAD

**Issue by Zeemgeem** [Grammernatzi/XIVComboPlugin#150]
I know the plugin just became available, but I wanted to compile everything I noticed from testing, if just to make the dev job easier if you might have missed something. I probably didn't notice everything either though.

BLM:
With Ley Lines updating into Retrace as a vanilla feature I think Between the Lines could possibly be moved to Aetherial Manipulation while Ley Lines are up and no ally is targeted.

RDM:
some weird quirks at the moment make Jolt3 higher potency than Verfire/Verstone from 84 to 94. Ideally, then the combo system shouldn't use them at all in those level ranges.

DNC:
Last Dance and standard step are mutually exclusive.

DRG:
Dragon Sight combos can be removed.

**Comment by Grammernatzi** [comment]
BLM Aetherial Manipulation to BtL wouldn't work with mouseovers, which is how I use Aetherial Manipulation, so that wouldn't be a good idea. Last Dance I'm considering but DNC has so few buttons that I'll just save it for when I eventually level it. Also, verfire/verstone are still better because they give more mana gauge, I believe. But yeah, I forgot about Dragon Sight being removed.

**Comment by Grammernatzi** [comment]
I have now added all of these except the BLM one because I don't think that would fit due to most BLMs using mouseover for Aetherial Manipulation. Maybe there will be a better option in the future.
