### ISSUE TITLE
BLM Blizzard 1/3 Feature

### ISSUE THREAD

**Issue by Nypheena** [Grammernatzi/XIVComboPlugin#151]
Unless I'm misunderstanding it this option
![image](https://github.com/Grammernatzi/XIVComboPlugin/assets/16083155/55034103-dfca-45ed-8828-aa23d8decda9)
Is meant to swap back to b1 once you're in umbral 3 right? it doesn't seem to do that sadly, would be really beneficial now with the mp changes and you're scaled down so no b4

Besides that thank you so much for updating this so I could use it right away with dalamud beta, it was really difficult to play the blm with the button bloat and new mp changes

**Comment by Grammernatzi** [comment]
No, the description for that is just wrong, it just changes Blizzard 1 into 3 if you don't have Blizzard 3 unlocked yet so it's really just a level sync feature and I forgot to change the description. Blizzard 4 completely replaces Blizzard 1 for MP restoration once you get it and the Fire/Blizz 4 switch already turns into Blizzard 1 when you are synced below Blizzard 4.

**Comment by Grammernatzi** [comment]
I think someone *else* got annoyed at it working the way you described, because they still wanted to use Blizzard 3 at UI3 for whatever reason. I forget, though, because it has been a while. But I will take a look at it. It doesn't seem like it'd conflict with anything since there's no reason you'd use Blizzard 3 while at full UI3 that I can think of, and I can't remember why I changed it to this way in the first place.

**Comment by Grammernatzi** [comment]
Yeah, so gauge.umbralIceStacks is... really weird right now? It seems to just be a true or false value if it's above one or something. So I just simply did a check for if it's less-than-or-equal to 2 to bring out blizzard 3, and since it's 0 when you only have one stack, it seems to work, and hopefully won't bug out if it becomes an actual number. Either way, it works for now and I'm pushing this very soon.

**Comment by Grammernatzi** [comment]
I'm a Black mage main, myself, but I'm not leveling it for a bit since I am getting the new jobs to 90 and then doing a bit of MSQ as Viper for flavor. So I have not been testing it as much as I otherwise would have been. But once MSQ is done, I will be playing it a lot.
