### ISSUE TITLE
Suggestion [BLM]

### ISSUE THREAD

**Issue by Alkeyd** [Grammernatzi/XIVComboPlugin#159]
Me again!
And if Fire 3 turn into Blizzard 3 when on Astral Fire (Fire Rotation) and don't have Firestarter Buff and back to Fire 3 when in Umbral Ice (Ice Rotation)

**Comment by Grammernatzi** [comment]
What about if you have only one stack of UI because you transposed? In that situation, sometimes you want to use Fire 3, sometimes you want to use Blizzard 3 instead of Umbral Soul, it entirely depends on how much MP you have, and that's a check that's a bit hard to add a solid 'if' statement for. Also, you don't always want to Fire 3 when you're out of combat, like if you're low on MP, and I'm not sure I want to, at the moment, add a feature with so many conditional checks.

**Comment by Alkeyd** [comment]
Sorry for the delay, I was sleeping, I don't play BLM, it was a friend's suggestion, but it really seems to be something very situational

**Comment by Grammernatzi** [comment]
No problem, it's just hard to work on something like this for two things that aren't mutually exclusive (like Fire 4/Blizzard 4 and, once you get Fire 3/Blizzard 3, Fire 1 and Blizzard 1). It'd be a lot of work to make sure it doesn't mess things up and I don't think I'm really up to that task right now. If someone else wanted to work on it and test it out and push it via a pull request, though, if they figured out how to make it work perfectly, then maybe.

**Comment by Alkeyd** [comment]
I was going to close the chat but I thought of something for WAR, that he could have an extra option to transform the combo into AOE in Decimate whenever he has 50+ Gauge, for DG it would be very useful since he has Infuriate that fills 50 Gauge and ends up giving Overcap

**Comment by Grammernatzi** [comment]
Main reason I didn't do something like this is because it can be a bit too automatic and because there's already a fell cleave to decimate feature to save buttons. I did once have a fell cleave/decimate to infuriate feature though, I could perhaps add that again?
