### ISSUE TITLE
Viper's suggestion

### ISSUE THREAD

**Issue by gitnario** [Grammernatzi/XIVComboPlugin#163]
Hunter's Coil -> Twinfang Bite -> Twinblood Bite
Swiftskin's Coil -> Twinfang Bite -> Twinfang Bite
Combine Reawaken combos into one
Combine Uncoiled Fury combo into one

I tried to see if I could make one myself, but it was too difficult for me, being new to github...

**Comment by Grammernatzi** [comment]
So with fully one-button stuff like this for Viper, I wasn't going to go the way I did with Reaper and make so much stuff one-button, instead focusing on making everything just accessible with the base combos so the hotbar was far more condensed; however, I was going to add it if it ever showed up in XIVCombo Expanded or base XIVCombo. So, if you want features that automatically put everything in order on one button, I would recommend asking there, at https://github.com/MKhayle/XIVComboExpanded.

**Comment by doomsz** [comment]
looks like khayle VPR combos got updated alot.. can you please add them aswell ?

**Comment by Grammernatzi** [comment]
I will look at it. I do want to avoid Viper becoming the bloated mess that Reaper became, though, so I will be trying to avoid anything redundant.

**Comment by doomsz** [comment]
imo maybe wait for after patch ? they said they gonna change vpr abit

**Comment by SylvAlternate** [comment]
Not sure if this is the right place to ask, but would it be possible to have Writhing Snap turn into Uncoiled Fury if you have Rattling Coils (or vice versa)? like the Furious Steel Fang feature but without replacing your melee

**Comment by Grammernatzi** [comment]
> Not sure if this is the right place to ask, but would it be possible to have Writhing Snap turn into Uncoiled Fury if you have Rattling Coils (or vice versa)? like the Furious Steel Fang feature but without replacing your melee

Yeah, I was honestly thinking of that. I can whip that up real quick.

**Comment by Grammernatzi** [comment]
Looking at the new 'PVP-style' combos in regular Expanded and I don't like how a lot of them remove decision making. I made that mistake with Reaper early on (though I brought an option on to bring it back and use that myself). I'll bring on any that don't impact decision making, but yeah. And while I doubt they'll remove how these actions flow together, I'll wait until 7.01 before doing anything.

**Comment by doomsz** [comment]
my only complaint abt this job is too damn much double weave... positional were fine

**Comment by Grammernatzi** [comment]
I personally don't mind the double weaving so much because they increase the GCD to compensate on the moves that require it, but I don't have much latency. If you do, is that even with NoClippy enabled? Personally, I just like having a busy job. I think there should be options for that in the game and that not every job needs to be made for the same kind of person.

**Comment by MKhayle** [comment]
> Looking at the new 'PVP-style' combos in regular Expanded and I don't like how a lot of them remove useful decision making such as choosing what positional to use when there's no reason to explicitly pick one, like for the Coil moves. I made that mistake with Reaper early on (though I brought an option on to bring it back and use that myself) as well as some other jobs, but I mainly keep those features for legacy reasons since people still use them and simply gave options instead. I'll bring on any that don't impact useful decision making, like the ones the OP mentioned, but yeah. And while I doubt they'll remove how these actions flow together, I'll wait until 7.01 before doing anything. They did mention removing some of the positionals, which I am personally very against, but Squeenix does what Squeenix does.

about this: we're re-designing Expanded from the ground and you can check it out there https://github.com/MKhayle/XIVComboExpanded/issues/323
It's currently still in a very PoC state, but some options will get sorted better because so far normal vs secret is a super weird design since 7.0 baked-in combo standard

**Comment by MKhayle** [comment]
(the PvP-style combos are a bit weird but tbh the job itself is a bit weird 🌵 )

**Comment by kaedys** [comment]
I personally think the PVP combos are _too_ condensed, but to each their own.  Personally, I only really want a combo to merge the Coils down onto the Fangs (Dreadwinder follow-ups down onto the base ST combo buttons), and the same for AoE, an all-in-one Reawaken button, and merging Serpent's Tail into the two Twin oGCD buttons (because 3 "various oGCDs will appear here" buttons is just too many, imo.  I don't have the mouse buttons for it).

The Reawaken and Serpent's Tail are in MKhayle's already, and I have a PR ready for the Coil/Den merge into the standard combo buttons, just waiting for 323 to be completed so I don't cause more merge conflicts for MKhayle.

**Comment by Grammernatzi** [comment]
I think I will just add the ones that the OP requested for now, then, since those are also in Expanded. Anything more automatic than that and I'm not too sure, I really like how I've set up Viper for my own personal play and that's basically how it works atm in this fork. But I know obviously that I'm not the only one using it and so I'll add stuff as needed as long as it doesn't reach the point where it's just 'you should probably install SlothCombo instead'.

**Comment by Grammernatzi** [comment]
Added.
