### ISSUE TITLE
WHM Glare IV

### ISSUE THREAD

**Issue by Nypheena** [Grammernatzi/XIVComboPlugin#174]
I was thinking, an option for whm that puts glare IV onto the regular glare button(higher potency and instant cast, rarely a time you'd wanna regular glare over it) would be neat, while I'm not level 92 for my whm yet I have presence of mind on a cooldown button which with 120s recast is not designed to be used often but currently it swaps into that, you can place glare IV on its own on hotbar but I personally don't have the space lol

**Comment by Grammernatzi** [comment]
Because Glare IV is a movement option on a job that doesn't have many, I don't think this would be a good idea. You have to blow all the Glare IVs during raid buffs but that still leaves you with 4 regular GCDs to use and you may want to frontload those if movement is about to be heavy (like during P10 Savage, for example), or intersperse them. So what I'm instead going to do is put it on Holy like I did with Afflatus Misery, a similar movement option, because in AoE you'll usually just want to blow it ASAP and that way it's put on an attack instead of a cooldown button during burst.

**Comment by Grammernatzi** [comment]
Added, but please let me know if this works for you; the other idea was to use Assize instead.
