### ISSUE TITLE
Feature Enhancement: 159 Bhava to Hellfrog also after Katon/Raiton

### ISSUE THREAD

**Issue by Lunatory** [Grammernatzi/XIVComboPlugin#181]
Hello, could you make feature # 159 Bhavacakra to Hellfrog Medium also swap to Hellfrog after a Katon/Goka Mekkyaku and Bhava after Raiton/Hyosho Ranyru?

While doing dungeons yesterday I noticed, coming from a boss and going into more fodder, my first casts are Ninjutsu, leading to my Bhava still being Bhava and not Hellfrog yet. Minor issue if detection is harder for Ninjutsus, especially since it's realistically only applicable to dungeons, but would still be a nice addition if you could implement this.

**Comment by Grammernatzi** [comment]
Can't do this with the current tracking, sorry. It's tracking last used combo actions, not last used move, and the Ninjutsu are specifically not combo actions so that they don't break your combo. I could add that, but it'd be a fair bit of work. If Expanded adds something like tracking the last used actionID then I may be able to borrow that. Until then, I'll have to close this because of the amount of work it'd require. But I definitely understand the desire and it makes perfect sense, it's just not feasible without a lot of work.
