### ISSUE TITLE
Fire 2 feature option

### ISSUE THREAD

**Issue by jtabox** [Grammernatzi/XIVComboPlugin#83]
Hey, correct me if I'm wrong here, but shouldn't Fire 2 Feature keep Fire 2 when you have 2 Umbral Hearts, even if you have Enhanced Flare?
Supposedly in the AOE rotation you should be casting 3 Fire 2's and then 2 Flares, but currently the addon does 2 Fire 2's and then 2 Flares, because as soon as I cast my second Fire 2 I get Enhanced Flare so Fire 2 becomes Flare even though I still have 2 Umbral Hearts, so essentially I miss 1 Fire 2 cast. At least that's how it is for me at level 80.
Is it possible to add the option for (High) Fire 2 to become Flare only when I have 1 Umbral Heart, regardless of Enhanced Flare?

Edit: I saw now that someone else has made the exact same suggestion in Daemitus' fork, they even wrote the required code.
https://github.com/daemitus/XIVComboPlugin/issues/100

**Comment by Grammernatzi** [comment]
I could add an option, the math I did was that the extra Fire 2 is only marginally higher potency and that's only if it doesn't cost you an extra flare (which, it often does cost you one). So I decided, since the feature is for braindead aoe, it might as well do the rotation that, on average, provides higher potency per second in most situations, and figured people would just disable the feature if they want more manual control. I could add an option, though, if people still really want that.

**Comment by jtabox** [comment]
Nah, not too fussed about it, if you say it's only marginally higher potency.

**Comment by Grammernatzi** [comment]
I mean, I could see a case for it, to be fair, if someone wants to simply just press the button and then press flare early if they want, since that'd simplify the aoe rotation. So, I might as well add the option, but probably with a disclaimer about how the rotation works.
