### ISSUE TITLE
Little proposal for WHM

### ISSUE THREAD

**Issue by Me1j1n** [Grammernatzi/XIVComboPlugin#88]
Please add option to change Cure to Cure II when Freecure proc

**Comment by Grammernatzi** [comment]
I thought about this but I also think freecure is a sin, so I would prefer not to encourage using it as the amount of white mages spamming cure after they get cure II is already way too much.

**Comment by Me1j1n** [comment]
>but I also think freecure is a sin

why? ^_^'
I think WHM have most manasustaining problem among all healers, especially when he starts casting under the Presence of Mind, because Lucid Dreaming is the only way WHM can regen his MP, unlike other healers. So I think this feature can little help him with this problem. Why spend MP on Cure when you can cast Cure II for free, right? The problem is Freecure have only 15% chance to proc and lasts only 15 seconds. That's why many WHMs just ignore this trait, little chance to proc, little duration time, it's just not worthy to pay attention on procs. Besides, there is one problem. For example, I use your feature Cure II to Afflatus Solace when lily is up, so I don't need to keep Solace on hotbar, but if I have lily and Freecure proc at the same time, I just can't use Cure II, I must use Solace. It's not big problem, of course, I just thinking how to make Freecure trait little more usefull =)

**Comment by Grammernatzi** [comment]
The mana-sustaining problem on WHM isn't from single-target healing. They use Afflatus, Tetra, and Benediction to do that for free. Most of WHMs MP problems, at the moment, come from the gradual drain on MP from DPS that isn't currently offset by anything outside of lucid dreaming and assize. They used to have Thin Air to help, but since Thin Air's nerf, they've not been able to use it for the former, which is why they are really hurting for mana. So, Freecure doesn't help with WHM's mana problems, because they already are doing the job it provides for free, and most of the mana drain is coming from DPS causing a net negative drain.

Anyway, at the moment, if someone pushes it in a pull request, then I will add it. But at the moment, I
